import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/sidebar";
import PriceRow from "@/components/elements/priceRow";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-900 text-zinc-50">
      <body className={`${inter.className} flex min-h-screen`}>
        <Sidebar />
        <div className="w-full">
          <PriceRow />
          <div className=" w-11/12 mx-auto mt-7">{children}</div>
        </div>
      </body>
    </html>
  );
}
